-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 16:35:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/*SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';*/

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
/*CREATE SCHEMA IF NOT EXISTS `acessaciti` DEFAULT CHARACTER SET utf8 ;
USE `acessaciti` ;*/

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------

/*CREATE TABLE IF NOT EXISTS `acessaciti`.`category` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(120) NULL,
  `categoryId` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_category_category`
    FOREIGN KEY (`categoryId`)
    REFERENCES `acessaciti`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`urgencylevel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`urgencylevel` (
  `id` VARCHAR(36) NOT NULL,
  `description` LONGTEXT NULL,
  `priority` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(120) NULL,
  `email` VARCHAR(200) NULL,
  `password` LONGTEXT NULL,
  `criationdate` DATETIME NULL,
  `profileurl` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`reportstatus` (
  `id` VARCHAR(36) NOT NULL,
  `description` LONGTEXT NULL,
  `daned` TINYINT NULL,
  `approved` TINYINT NULL,
  `review` TINYINT NULL,
  `inprogress` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`report` (
  `id` VARCHAR(36) NOT NULL,
  `categoryId` VARCHAR(36) NOT NULL,
  `urgencyLevelId` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `reportstatusId` VARCHAR(36) NOT NULL,
  `title` VARCHAR(200) NULL,
  `description` LONGTEXT NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(10,8) NULL,
  `accuracy` DECIMAL(10,8) NULL,
  `creationdate` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_report_category1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `acessaciti`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_table11`
    FOREIGN KEY (`urgencyLevelId`)
    REFERENCES `acessaciti`.`urgencylevel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_reportstatus1`
    FOREIGN KEY (`reportstatusId`)
    REFERENCES `acessaciti`.`reportstatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportattachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`reportattachment` (
  `id` VARCHAR(36) NOT NULL,
  `reportId` VARCHAR(36) NOT NULL,
  `mediatype` VARCHAR(45) NULL,
  `url` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reportattachment_report1`
    FOREIGN KEY (`reportId`)
    REFERENCES `acessaciti`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportsolution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`reportsolution` (
  `id` VARCHAR(36) NOT NULL,
  `reportId` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `reportstatusId` VARCHAR(36) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reportsolution_report1`
    FOREIGN KEY (`reportId`)
    REFERENCES `acessaciti`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportsolution_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportsolution_reportstatus1`
    FOREIGN KEY (`reportstatusId`)
    REFERENCES `acessaciti`.`reportstatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportsolutionattachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`reportsolutionattachment` (
  `id` VARCHAR(36) NOT NULL,
  `reportsolutionId` VARCHAR(36) NOT NULL,
  `mediatype` VARCHAR(45) NULL,
  `url` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reportsolutionattachment_reportsolution1`
    FOREIGN KEY (`reportsolutionId`)
    REFERENCES `acessaciti`.`reportsolution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`reportcomment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`reportcomment` (
  `id` VARCHAR(36) NOT NULL,
  `reportId` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `comment` LONGTEXT NULL,
  `approved` TINYINT NULL,
  `creationdate` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reportcomment_report1`
    FOREIGN KEY (`reportId`)
    REFERENCES `acessaciti`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportcomment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`roles` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`userroles` (
  `id` VARCHAR(36) NOT NULL,
  `roles_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_userroles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `acessaciti`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userroles_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportclassification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`reportclassification` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `report_id` VARCHAR(36) NOT NULL,
  `rating` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reportclassification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportclassification_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `acessaciti`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interactionhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`interactionhistory` (
  `id` VARCHAR(36) NOT NULL,
  `newreportstatusid` VARCHAR(36) NOT NULL,
  `reportid` VARCHAR(36) NOT NULL,
  `oldreportstatusid` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `description` LONGTEXT NULL,
  `creationdate` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_interactionhistory_reportstatus1`
    FOREIGN KEY (`newreportstatusid`)
    REFERENCES `acessaciti`.`reportstatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactionhistory_report1`
    FOREIGN KEY (`reportid`)
    REFERENCES `acessaciti`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactionhistory_reportstatus2`
    FOREIGN KEY (`oldreportstatusid`)
    REFERENCES `acessaciti`.`reportstatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interactionhistory_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportinprogress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`reportinprogress` (
  `id` VARCHAR(36) NOT NULL,
  `report_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `interactionhistoryId` VARCHAR(36) NOT NULL,
  `creationdate` DATETIME NULL,
  `estimatadefinishdate` DATETIME NULL,
  `startdate` DATETIME NULL,
  `donedate` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reportinprogress_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `acessaciti`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportinprogress_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportinprogress_interactionhistory1`
    FOREIGN KEY (`interactionhistoryId`)
    REFERENCES `acessaciti`.`interactionhistory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cityhall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`cityhall` (
  `id` VARCHAR(36) NOT NULL,
  `cityid` varchar(36),
  `name` VARCHAR(200) NULL,
  `CNPJ` CHAR(14) NOT NULL,
  `verified` TINYINT NULL,
  `address` VARCHAR(200) NULL,
  `number` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(120) NULL,
  `zipcode` CHAR(8) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cityhall_city`
    FOREIGN KEY (`cityid`)
    REFERENCES `acessaciti`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cityhallrelateduser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`cityhallrelateduser` (
  `id` VARCHAR(36) NOT NULL,
  `userid` VARCHAR(36) NOT NULL,
  `cityhallid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cityhallrelateduser_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cityhallrelateduser_cityhall1`
    FOREIGN KEY (`cityhallid`)
    REFERENCES `acessaciti`.`cityhall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usernotification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`usernotification` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(45) NULL,
  `shortdescription` VARCHAR(160) NULL,
  `urlclickdescription` LONGTEXT NULL,
  `read` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usernotification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`state` (
  `id` VARCHAR(36) NOT NULL,
  `ufcode` CHAR(2) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`city` (
  `id` VARCHAR(36) NOT NULL,
  `stateid` VARCHAR(36) NOT NULL,
  `ibgecode` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(10,8) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_city_table11`
    FOREIGN KEY (`stateid`)
    REFERENCES `acessaciti`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interacitonhistorycomment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acessaciti`.`interacitonhistorycomment` (
  `id` VARCHAR(36) NOT NULL,
  `interactionhistoryid` VARCHAR(36) NOT NULL,
  `interacitonhistorycommentid` VARCHAR(36) NULL,
  `comment` LONGTEXT NULL,
  `userid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_interacitonhistorycomment_interactionhistory1`
    FOREIGN KEY (`interactionhistoryid`)
    REFERENCES `acessaciti`.`interactionhistory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interacitonhistorycomment_interacitonhistorycomment1`
    FOREIGN KEY (`interacitonhistorycommentid`)
    REFERENCES `acessaciti`.`interacitonhistorycomment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interacitonhistorycomment_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `acessaciti`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `acessaciti`.`reasondany` (
	`id` varchar(36),
    `description` longtext,
    primary key(`id`)
)ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;*/

